USE Racing
GO

CREATE TABLE RaceParticipant (
	ParticipantId UNIQUEIDENTIFIER NOT NULL,
	DriverId UNIQUEIDENTIFIER NOT NULL,
	RaceId UNIQUEIDENTIFIER NOT NULL
	)

CREATE TABLE Race (
	RaceId UNIQUEIDENTIFIER NOT NULL,
	RaceTrackId UNIQUEIDENTIFIER NOT NULL
	)